#!/usr/bin/env node
// One-time metadata enrichment — fetches genres, descriptions, and poster paths from TMDB.
// Usage: node enrich.mjs  (reads TMDB_API_KEY from .env)
// Outputs: metadata.js (committed and loaded by the browser app)
// Re-run safely — skips titles already in metadata.js. To retry failures, delete their keys.

import { readFileSync, writeFileSync, existsSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import vm from 'vm';
import https from 'https';

const __dirname = dirname(fileURLToPath(import.meta.url));

// Load .env
const envPath = join(__dirname, '.env');
if (existsSync(envPath)) {
  readFileSync(envPath, 'utf8').split('\n').forEach(line => {
    const [k, ...rest] = line.split('=');
    if (k?.trim() && rest.length) process.env[k.trim()] = rest.join('=').trim();
  });
}

const TMDB_KEY = process.env.TMDB_API_KEY;
if (!TMDB_KEY || TMDB_KEY === 'your_tmdb_api_key_here') {
  console.error('Add your TMDB_API_KEY to the-vault/.env');
  process.exit(1);
}

const OUT = join(__dirname, 'metadata.js');
const CHECKPOINT = 100; // write to disk every N titles

// TMDB genre ID → internal slug
const TMDB_GENRES = {
  28:'action', 12:'adventure', 16:'animated', 35:'comedy', 80:'crime',
  99:'documentary', 18:'drama', 10751:'family', 14:'fantasy', 36:'history',
  27:'horror', 10402:'musical', 9648:'mystery', 10749:'romance', 878:'scifi',
  53:'thriller', 10752:'war', 37:'western',
  // TV-specific genre IDs
  10759:'action', 10762:'animated', 10763:'documentary', 10765:'scifi',
  10766:'drama', 10768:'war',
};

// Load library data via vm sandbox (library.js is a browser global script, not a module).
// Replace top-level `const` with `var` so declarations attach to the sandbox global.
const sandbox = {};
vm.createContext(sandbox);
vm.runInContext(readFileSync(join(__dirname, 'library.js'), 'utf8').replace(/^const /gm, 'var '), sandbox);
const { RAW } = sandbox;

// Resume: load existing metadata.js if present
let metadata = {};
if (existsSync(OUT)) {
  try {
    const ctx = {};
    vm.createContext(ctx);
    vm.runInContext(readFileSync(OUT, 'utf8').replace(/^const /gm, 'var '), ctx);
    metadata = ctx.METADATA || {};
    console.log(`Resuming — ${Object.keys(metadata).length} titles already processed\n`);
  } catch(e) {
    console.log('Could not parse existing metadata.js, starting fresh\n');
  }
}

function get(url) {
  return new Promise((resolve, reject) => {
    https.get(url, res => {
      let d = '';
      res.on('data', c => d += c);
      res.on('end', () => { try { resolve(JSON.parse(d)); } catch(e) { reject(e); } });
    }).on('error', reject);
  });
}

const sleep = ms => new Promise(r => setTimeout(r, ms));

async function searchTMDB(clean, year, type) {
  const q = encodeURIComponent(clean);
  const base = `https://api.themoviedb.org/3/search/${type}?api_key=${TMDB_KEY}&query=${q}`;
  const yearParam = year ? `&${type === 'tv' ? 'first_air_date_year' : 'year'}=${year}` : '';
  const dateKey = type === 'tv' ? 'first_air_date' : 'release_date';

  // Try with year
  if (year) {
    try {
      const d = await get(`${base}${yearParam}`);
      const match = (d.results || []).find(r => {
        const ry = parseInt((r[dateKey] || '').slice(0, 4));
        return Math.abs(ry - year) <= 2;
      });
      if (match) return match;
    } catch(e) {}
    await sleep(270);
  }

  // Fall back to no-year search
  try {
    const d = await get(base);
    return (d.results || [])[0] || null;
  } catch(e) { return null; }
}

function toEntry(result, type) {
  if (!result) return null;
  const ids = result.genre_ids || (result.genres || []).map(g => g.id);
  const genres = [...new Set(ids.map(id => TMDB_GENRES[id]).filter(Boolean))];
  const dateKey = type === 'tv' ? 'first_air_date' : 'release_date';
  return {
    genres,
    description: (result.overview || '').slice(0, 500),
    poster: result.poster_path || null,
  };
}

function save() {
  writeFileSync(OUT, `// Generated by enrich.mjs — do not edit manually\nconst METADATA = ${JSON.stringify(metadata, null, 2)};\n`, 'utf8');
}

async function main() {
  const all = [];
  for (const [cat, titles] of Object.entries(RAW)) {
    for (const title of titles) all.push({ title, cat });
  }

  const todo = all.filter(({ title }) => !(title in metadata));
  console.log(`${todo.length} to process, ${all.length - todo.length} already done`);
  console.log(`Estimated time: ~${Math.round(todo.length * 0.27 / 60)} minutes\n`);

  let done = 0, found = 0, missed = 0;

  for (const { title, cat } of todo) {
    const ym = title.match(/\((\d{4})\)/);
    const year = ym ? +ym[1] : null;
    const clean = title.replace(/\s*\(\d{4}\)\s*/, '').trim();
    const tmdbType = cat === 'tv' ? 'tv' : 'movie';

    const result = await searchTMDB(clean, year, tmdbType);
    await sleep(270); // ~3.7 req/s — well under TMDB's 40/10s limit

    const entry = toEntry(result, tmdbType);
    if (entry) {
      metadata[title] = entry;
      found++;
    } else {
      metadata[title] = { genres: [], description: '', poster: null };
      missed++;
      if (missed <= 30 || missed % 100 === 0) {
        console.log(`  ✗ not found: ${title}`);
      }
    }

    done++;
    if (done % CHECKPOINT === 0) {
      save();
      const pct = Math.round(done / todo.length * 100);
      console.log(`${pct}%  ${done}/${todo.length}  (${found} matched, ${missed} missed)`);
    }
  }

  save();
  console.log(`\nDone. ${found} enriched, ${missed} not found in TMDB.`);
  console.log(`metadata.js written — commit it and redeploy.`);
}

main().catch(err => { console.error(err); process.exit(1); });
