// Hand-transcribed from obsidian/3 Resources/Entertainment/Watchlist.md
// ("## 🍂 Fall 2026 — Spooky Season by Theme" section). Not parsed at runtime —
// this file is the source of truth for the FALL 2026 tab. Re-transcribe by hand
// if the Watchlist section changes.
//
// Item shape: { title, year?, date?, platform?, note?, focused?, fillsGap?, libraryKey? }
// libraryKey (owned items only) is the exact RAW string in library.js this title
// matches, or null if no exact match was found.
const FALL_2026 = {
  checkedDate: "2026-09-28",

  intro: "Built 2026-09-28 off what's been landing lately: Lanterns, Widow's Bay, Pluribus. The common thread is a genre premise played dead straight in one specific small place, with a mystery that unspools over a season and dry humor underneath the dread. In the Vault = already owned (check the-vault/library.js). Missing = gaps worth acquiring.",

  startHere: "A couple's show → Three Pines or Deadloch. Movie night → A Haunting in Venice. If you fill only one gap → Twin Peaks.",

  themes: [
    {
      n: 1,
      title: "Something's Wrong in This Town",
      tagline: "The Widow's Bay / Lanterns lane. Small places, slow reveals.",
      owned: [
        { title: "Deadloch", note: "Tasmanian small-town murder mystery that's actually funny. Closest match to Widow's Bay.", libraryKey: "Deadloch" },
        { title: "Three Pines", note: "Quebec village murders, Inspector Gamache. Literally autumnal.", libraryKey: "Three Pines" },
        { title: "Dublin Murders", note: "Tana French. Kids vanished in the woods, a hint of the supernatural.", libraryKey: "Dublin Murders" },
        { title: "Fargo", note: "Series.", libraryKey: "Fargo" },
        { title: "Fargo", year: 1996, note: "The 1996 film.", libraryKey: "Fargo (1996)" },
        { title: "True Detective", libraryKey: "True Detective" },
        { title: "Dark Winds", libraryKey: "Dark Winds" },
        { title: "Outer Range", libraryKey: "Outer Range" },
        { title: "Castle Rock", libraryKey: "Castle Rock" },
        { title: "The Devil's Hour", libraryKey: "The Devil's Hour" },
        { title: "Hot Fuzz", year: 2007, libraryKey: "Hot Fuzz (2007)" },
        { title: "Wind River", year: 2017, libraryKey: "Wind River (2017)" },
      ],
      missing: [
        { title: "Twin Peaks (S1–2 + Fire Walk With Me)", note: "The ur-text for everything above. Biggest hole in the vault." },
        { title: "Midnight Mass", year: 2021, platform: "Netflix", note: "Mike Flanagan. Island town, slow reveal. Widow's Bay's closest cousin." },
        { title: "Broadchurch S1", year: 2013, platform: "ITV", note: "Seaside-town child murder. Whole town as suspect pool." },
        { title: "Mare of Easttown", year: 2021, platform: "HBO", note: "Kate Winslet. Pennsylvania small-town procedural. Immaculate." },
      ],
    },
    {
      n: 2,
      title: "Whodunnit Night",
      tagline: "Closed-circle puzzles, drawing-room reveals.",
      owned: [
        { title: "A Haunting in Venice", year: 2023, note: "Halloween-night séance. The October Poirot.", libraryKey: "A Haunting In Venice (2023)" },
        { title: "Knives Out", year: 2019, libraryKey: "Knives Out (2019)" },
        { title: "Glass Onion", year: 2022, libraryKey: "Glass Onion A Knives Out Mystery (2022)" },
        { title: "Clue", year: 1985, libraryKey: "Clue (1985)" },
        { title: "Murder by Death", year: 1976, libraryKey: "Murder By Death (1976)" },
        { title: "See How They Run", year: 2022, libraryKey: "See How They Run (2022)" },
        { title: "Identity", year: 2003, note: "Motel in a storm, ten strangers. Great October movie.", libraryKey: "Identity (2003)" },
        { title: "Bad Times at the El Royale", year: 2018, libraryKey: "Bad Times At The El Royale (2018)" },
        { title: "And Then There Were None", year: 2015, platform: "BBC", libraryKey: "And Then There Were None" },
        { title: "The ABC Murders", platform: "BBC", libraryKey: "The ABC Murders" },
        { title: "Poker Face", libraryKey: "Poker Face" },
        { title: "Only Murders in the Building", libraryKey: "Only Murders in the Building" },
      ],
      missing: [
        { title: "Wake Up Dead Man", year: 2025, note: "The gothic, church-set Knives Out. The most October of the three." },
        { title: "Gosford Park", year: 2001, note: "Altman. Country-house murder, upstairs/downstairs." },
        { title: "Sleuth", year: 1972, note: "Olivier and Caine, one house, a game of one-upmanship." },
        { title: "The Last of Sheila", year: 1973, note: "Stephen Sondheim co-wrote this puzzle-box movie. A yacht party. Underseen gem." },
      ],
    },
    {
      n: 3,
      title: "The Pluribus Lane",
      tagline: "Weird premise, played straight, patient unspool.",
      owned: [
        { title: "Counterpart", note: "Underseen, exactly this register.", libraryKey: "Counterpart" },
        { title: "Tales from the Loop", libraryKey: "Tales from the Loop" },
        { title: "Russian Doll", libraryKey: "Russian Doll" },
        { title: "Homecoming", libraryKey: "Homecoming" },
        { title: "Legion", libraryKey: "Legion" },
        { title: "Take Shelter", year: 2011, libraryKey: "Take Shelter (2011)" },
        { title: "No One Will Save You", year: 2023, libraryKey: "No One Will Save You (2023)" },
        { title: "Donnie Darko", year: 2001, libraryKey: "Donnie Darko DIRECTORS CUT (2001)" },
      ],
      missing: [
        { title: "The Leftovers", note: "HBO, 2014–2017. The one to push hardest if Pluribus landed." },
        { title: "Station Eleven", year: 2021, platform: "HBO Max", note: "Post-collapse, a traveling Shakespeare troupe. Beautiful." },
        { title: "Devs", year: 2020, platform: "FX/Hulu", note: "Alex Garland. Tech-cult determinism thriller." },
        { title: "Coherence", note: "Already on this list but not in the vault." },
        { title: "The Invitation", note: "Already on this list but not in the vault." },
        { title: "Lodge 49", note: "Already on this list but not in the vault." },
        { title: "Dark", note: "Already on this list but not in the vault." },
      ],
    },
    {
      n: 4,
      title: "Cozy Fall Canon",
      tagline: "The comfort classics. Blankets, cider, lights off.",
      owned: [
        { title: "Over the Garden Wall", note: "The most autumnal thing ever made. Ten 11-min episodes; save for the last two weeks of October.", libraryKey: "Over the Garden Wall" },
        { title: "It's the Great Pumpkin, Charlie Brown", year: 1966, libraryKey: "It's The Great Pumpkin, Charlie Brown (1966)" },
        { title: "Hocus Pocus", year: 1993, libraryKey: "Hocus Pocus (1993)" },
        { title: "Practical Magic", year: 1998, libraryKey: "Practical Magic (1998)" },
        { title: "The Addams Family", year: 1991, libraryKey: "The Addams Family (1991)" },
        { title: "Addams Family Values", year: 1993, libraryKey: "Addams Family Values (1993)" },
        { title: "Beetlejuice", year: 1988, libraryKey: "Beetlejuice (1988)" },
        { title: "Sleepy Hollow", year: 1999, libraryKey: "Sleepy Hollow (1999)" },
        { title: "Corpse Bride", year: 2005, libraryKey: "Corpse Bride (2005)" },
        { title: "Monster House", year: 2006, libraryKey: "Monster House (2006)" },
        { title: "Young Frankenstein", year: 1974, libraryKey: "Young Frankenstein (1974)" },
        { title: "Fantastic Mr. Fox", year: 2009, libraryKey: "Fantastic Mr Fox (2009)" },
        { title: "Trick 'r Treat", year: 2007, libraryKey: "Trick 'r Treat (2007)" },
        { title: "Halloween", year: 1978, libraryKey: "Halloween (1978)" },
        { title: "Halloween III: Season of the Witch", year: 1982, libraryKey: "Halloween III Season of The Witch (1982)" },
      ],
      missing: [
        { title: "ParaNorman", year: 2012, note: "Laika. A witch-curse mystery. The real gap here." },
        { title: "Coraline", year: 2009 },
        { title: "The Nightmare Before Christmas", year: 1993 },
        { title: "The Monster Squad", year: 1987, note: "Kids vs. the Universal monsters." },
        { title: "Something Wicked This Way Comes", year: 1983, note: "Bradbury's October carnival." },
      ],
    },
    {
      n: 5,
      title: "Gothic & Period Atmosphere",
      tagline: "Candlelight, fog, old houses.",
      owned: [
        { title: "Hannibal", note: "Series. The best-looking fall show ever made.", libraryKey: "Hannibal" },
        { title: "The Alienist", libraryKey: "The Alienist" },
        { title: "I Am the Night", libraryKey: "I Am The Night" },
        { title: "Penny Dreadful", libraryKey: "Penny Dreadful" },
        { title: "The Terror", libraryKey: "The Terror" },
        { title: "Interview with the Vampire", note: "Series.", libraryKey: "Interview with the Vampire" },
        { title: "The Changeling", year: 1980, libraryKey: "The Changeling (1980)" },
        { title: "The Night House", year: 2020, libraryKey: "The Night House (2020)" },
        { title: "From Hell", year: 2001, libraryKey: "From Hell (2001)" },
        { title: "Nosferatu", year: 2024, libraryKey: "Nosferatu (2024)" },
        { title: "The Lighthouse", year: 2019, libraryKey: "The Lighthouse (2019)" },
        { title: "House of Usher", year: 1960, note: "Corman/Poe double feature.", libraryKey: "House of Usher (1960)" },
        { title: "Pit and the Pendulum", year: 1961, note: "Corman/Poe double feature.", libraryKey: "Pit And The Pendulum (1961)" },
        { title: "Masque of the Red Death", year: 1964, note: "Corman/Poe double feature.", libraryKey: "The Masque Of The Red Death (1964)" },
        { title: "The Haunted Palace", year: 1963, note: "Corman/Poe double feature.", libraryKey: "The Haunted Palace (1963)" },
        { title: "The Devil Rides Out", year: 1968, note: "Plus the Corman/Poe double features.", libraryKey: "The Devil Rides Out (1968)" },
      ],
      missing: [
        { title: "The Others", year: 2001 },
        { title: "The Innocents", year: 1961 },
        { title: "The Haunting", year: 1963 },
        { title: "Crimson Peak", year: 2015, note: "del Toro gothic romance." },
        { title: "Don't Look Now", year: 1973, note: "Venice, grief, the red coat." },
      ],
    },
    {
      n: 6,
      title: "Procedural Dread",
      tagline: "Detectives, killers, the long dark.",
      owned: [
        { title: "The Silence of the Lambs", year: 1991, libraryKey: "The Silence Of The Lambs (1991)" },
        { title: "Red Dragon", year: 2002, libraryKey: "Red Dragon (2002)" },
        { title: "Mindhunter", libraryKey: "MINDHUNTER" },
        { title: "Sharp Objects", libraryKey: "Sharp Objects" },
        { title: "Longlegs", year: 2024, libraryKey: "Longlegs (2024)" },
        { title: "Shutter Island", year: 2010, libraryKey: "Shutter Island (2010)" },
      ],
      missing: [
        { title: "Zodiac", year: 2007, note: "Fincher. You own the 1971 exploitation Zodiac Killer, not this one." },
        { title: "Se7en", year: 1995 },
        { title: "Prisoners", year: 2013 },
        { title: "Memories of Murder", year: 2003, focused: true, note: "Bong Joon-ho." },
        { title: "Cure", year: 1997, focused: true, note: "Kiyoshi Kurosawa. Hypnotic." },
      ],
    },
    {
      n: 7,
      title: "Monster Classics Night",
      tagline: "Universal and Hammer, black-and-white, short runtimes, perfect with a double feature.",
      owned: [
        { title: "The Devil Rides Out", year: 1968, note: "Also in Gothic & Period Atmosphere.", libraryKey: "The Devil Rides Out (1968)" },
        { title: "Captain Kronos: Vampire Hunter", year: 1974, libraryKey: "Captain Kronos Vampire Hunter (1974)" },
        { title: "Young Frankenstein", year: 1974, note: "Also in Cozy Fall Canon.", libraryKey: "Young Frankenstein (1974)" },
        { title: "Dracula", year: 1992, libraryKey: "Dracula (1992)" },
      ],
      missingNote: "The whole Universal cycle streams on Peacock from Oct 1 — see the streaming guide below.",
      missing: [
        { title: "Dracula", year: 1931 },
        { title: "Frankenstein", year: 1931 },
        { title: "The Mummy", year: 1932 },
        { title: "The Invisible Man", year: 1933 },
        { title: "The Wolf Man", year: 1941 },
        { title: "Bride of Frankenstein", year: 1935, note: "The best of them all." },
      ],
    },
    {
      n: 8,
      title: "Anthology Nights",
      tagline: "Short-form scares for when you've got 30–45 minutes, not a full commitment.",
      owned: [
        { title: "Creepshow", note: "Series.", libraryKey: "Creepshow" },
        { title: "The Twilight Zone", note: "Original.", libraryKey: "The Twilight Zone (Original)" },
        { title: "The Twilight Zone", year: 2019, libraryKey: "The Twilight Zone (2019)" },
        { title: "Tales from the Darkside", year: 1990, libraryKey: "Tales From The Darkside (1990)" },
        { title: "Body Bags", year: 1993, libraryKey: "Body Bags (1993)" },
        { title: "Trick 'r Treat", year: 2007, libraryKey: "Trick 'r Treat (2007)" },
        { title: "V/H/S", year: 2012, note: "V/H/S series.", libraryKey: "V H S (2012)" },
        { title: "V/H/S/2", year: 2013, note: "V/H/S series.", libraryKey: "V H S 2 (2013)" },
        { title: "V/H/S/94", year: 2021, note: "V/H/S series.", libraryKey: "V H S 94 (2021)" },
        { title: "V/H/S/85", year: 2023, note: "V/H/S series.", libraryKey: "V H S 85 (2023)" },
        { title: "V/H/S Viral", year: 2014, note: "V/H/S series.", libraryKey: "V H S Viral (2014)" },
        { title: "Black Sabbath", year: 1963, libraryKey: "Black Sabbath (1963)" },
      ],
      missing: [
        { title: "Guillermo del Toro's Cabinet of Curiosities", year: 2022, platform: "Netflix", note: "8 standalone hours, several directors, Lovecraft adaptations. Episode picks: \"The Autopsy,\" \"Pickman's Model,\" \"The Viewing.\"" },
        { title: "Alfred Hitchcock Presents", platform: "Peacock", note: "30-minute twist-ending mysteries. Ideal couple's comfort watch." },
        { title: "Inside No. 9", platform: "BBC", note: "2014–2024. Shearsmith & Pemberton. Every episode is a different whodunnit, horror, or comedy in a single room. You'll find episodes on YouTube and BritBox." },
        { title: "Kwaidan", year: 1964, focused: true, note: "Japanese ghost-story anthology, painted sets, gorgeous." },
      ],
    },
    {
      n: 9,
      title: "Comfort Detectives",
      tagline: "Howcatchems and cozy mysteries. Low stakes, high charm, endlessly re-watchable.",
      owned: [
        { title: "Poker Face", note: "Also in Whodunnit Night.", libraryKey: "Poker Face" },
        { title: "Three Pines", note: "Also in Something's Wrong in This Town.", libraryKey: "Three Pines" },
        { title: "Murdoch Mysteries", libraryKey: "Murdoch Mysteries" },
        { title: "Only Murders in the Building", note: "Also in Whodunnit Night.", libraryKey: "Only Murders in the Building" },
        { title: "Psych", libraryKey: "Psych" },
        { title: "Agatha Christie's Partners in Crime", libraryKey: "Agatha Christie's Partners in Crime" },
      ],
      missing: [
        { title: "Columbo", platform: "Peacock", note: "1968–2003. The original howcatchem. Poker Face exists because of it. Start with \"Murder by the Book\" (S1E1, directed by Spielberg)." },
        { title: "Magpie Murders + Moonflower Murders", platform: "PBS Masterpiece", note: "Anthony Horowitz's nested whodunnit, a mystery inside a manuscript." },
        { title: "Agatha Christie's Poirot", note: "David Suchet, 1989–2013. The definitive long run." },
      ],
    },
    {
      n: 10,
      title: "Satanic Panic & VHS Nostalgia",
      tagline: "Late-80s/early-90s small towns, basement tapes, moral panic.",
      owned: [
        { title: "Late Night with the Devil", year: 2023, libraryKey: "Late Night With The Devil (2023)" },
        { title: "The House of the Devil", year: 2009, libraryKey: "The House Of The Devil (2009)" },
        { title: "Satanic Panic", year: 2019, libraryKey: "Satanic Panic (2019)" },
        { title: "Deer Camp '86", year: 2022, libraryKey: "Deer Camp 86 (2022)" },
        { title: "Summer of 84", year: 2018, libraryKey: "Summer Of 84 (2018)" },
        { title: "Deathgasm", year: 2015, libraryKey: "Deathgasm (2015)" },
        { title: "Studio 666", year: 2022, libraryKey: "Studio 666 (2022)" },
        { title: "Night of the Demons", year: 1988, libraryKey: "Night of the Demons (1988)" },
      ],
      missing: [
        { title: "Hysteria!", year: 2024, platform: "Peacock", note: "1989, a small Michigan town, a garage band posing as satanists for clout. Bruce Campbell. Very much in your lane." },
        { title: "Archive 81", platform: "Netflix", note: "Already on this list." },
      ],
    },
    {
      n: 11,
      title: "Cold-Weather Noir",
      tagline: "Scandi and Nordic crime. Grey skies, knit sweaters, long procedural seasons for November.",
      owned: [
        { title: "Fargo", note: "Also in Something's Wrong in This Town.", libraryKey: "Fargo" },
        { title: "Wind River", year: 2017, note: "Also in Something's Wrong in This Town.", libraryKey: "Wind River (2017)" },
        { title: "The Terror", note: "Also in Gothic & Period Atmosphere.", libraryKey: "The Terror" },
        { title: "Dead Snow", year: 2009, note: "The palate cleanser.", libraryKey: "Dead Snow (2009)" },
      ],
      missing: [
        { title: "The Killing / Forbrydelsen", focused: true, note: "Denmark, 2007–2012. The Danish original. One murder, 20 episodes, Sarah Lund's sweater." },
        { title: "Trapped / Ófærð", focused: true, note: "Iceland, 2015–. Storm-locked fishing town, a body in the harbor. Pure Widow's Bay weather." },
        { title: "The Bridge / Bron/Broen", focused: true, note: "Sweden/Denmark, 2011–2018. A body on the Øresund Bridge, split across the border." },
        { title: "Black Spot", note: "Already on this list, same lane." },
        { title: "Deadwind", note: "Already on this list, same lane." },
      ],
    },
  ],

  newThisSeason: [
    { title: "Carrie", platform: "Prime Video", date: "Oct 7", note: "Mike Flanagan's 8-episode King miniseries." },
    { title: "Below", platform: "Netflix", date: "Oct 8", note: "Newfoundland fishing town vs. a sea creature." },
    { title: "Yaga", platform: "AMC+", date: "Oct 23", note: "PI investigates a disappearance in a coastal town with magic. Sounds exactly Widow's Bay-shaped." },
    { title: "Yellowjackets S4", platform: "Paramount+", date: "Nov 20", note: "Final season. Earlier seasons are in the vault.", libraryKey: "Yellowjackets" },
  ],

  streaming: {
    note: "Checked late Sept 2026. Originals stay put; licensed titles rotate monthly, so re-check before a movie night. ⭐ = fills a gap from the themes above.",
    netflix: [
      { title: "Midnight Mass", year: 2021, fillsGap: true, note: "Flanagan. The Widow's Bay cousin." },
      { title: "The Haunting of Hill House", year: 2018, fillsGap: true, note: "Flanagan's best-known run. Hill House for dread — watch before Bly Manor." },
      { title: "The Haunting of Bly Manor", year: 2020, fillsGap: true, note: "Flanagan's best-known run. Gothic romance — the sequel anthology to Hill House." },
      { title: "The Fall of the House of Usher", year: 2023, fillsGap: true, note: "Flanagan does Poe as a pharma-dynasty satire. A perfect chaser for the Corman/Poe double features." },
      { title: "Wake Up Dead Man: A Knives Out Mystery", year: 2025, fillsGap: true, note: "Gothic church whodunnit." },
      { title: "The Sixth Sense", year: 1999, fillsGap: true, date: "Oct 1", note: "Arrives Oct 1." },
      { title: "Guillermo del Toro's Cabinet of Curiosities", year: 2022, fillsGap: true, note: "See Anthology Nights." },
      { title: "Bodies", year: 2023, note: "Four detectives in four eras find the same body in the same London alley. Pluribus-lane puzzle box, 8 episodes." },
      { title: "Monster: The Lizzie Borden Story", date: "Sept 17", note: "Ryan Murphy's anthology does the 1892 Fall River axe murders. Autumnal New England true crime." },
      { title: "Below", date: "Oct 8", note: "Josh Hartnett; a Newfoundland fishing town vs. something in the water." },
      { title: "Also on Netflix, already on the Watchlist", note: "Dark, Frankenstein (del Toro), Archive 81, Black Spot, Deadwind, Adolescence, Beef." },
    ],
    apple: [
      { title: "Widow's Bay + Pluribus", note: "Current. Next up in this lane is below." },
      { title: "Servant", note: "2019–2023. M. Night Shyamalan produced. A Philadelphia brownstone, a grieving couple, a nanny who is very wrong. Half-hour episodes, claustrophobic, darkly funny." },
      { title: "Bad Sisters", note: "2022–. Irish dark comedy. Four sisters, one monstrous brother-in-law, an insurance investigation. A whodunnit told backwards." },
      { title: "Slow Horses", note: "2022–. Gary Oldman's disgraced spies. Not spooky, but a great autumn couch show with the same dry humor." },
      { title: "Down Cemetery Road", year: 2025, note: "Emma Thompson, Mick Herron. A neighborhood explosion, a missing girl, a very British mystery." },
      { title: "Small Prophets", date: "Oct 7", note: "Mackenzie Crook (Detectorists) makes a man who summons magical spirits to find his missing girlfriend. Folk-whimsy, probably gentle." },
      { title: "Where's Wanda? S2", date: "Oct 21", note: "German dark comedy. Parents turn the neighborhood into a surveillance op to find their missing daughter." },
      { title: "Nocturne", date: "Oct 30", note: "Small-town detective, a serial killer, his own family in the crosshairs. Right in the Lanterns lane. New, unreviewed." },
      { title: "Also on Apple TV", note: "Severance (already on the Watchlist), Silo, Black Bird, Presumed Innocent, Dark Matter — all in the vault." },
    ],
    hboMax: [
      { title: "The Leftovers", fillsGap: true, note: "The one to push hardest post-Pluribus." },
      { title: "Mare of Easttown", year: 2021, fillsGap: true },
      { title: "Station Eleven", year: 2021, fillsGap: true },
      { title: "Twin Peaks: Fire Walk With Me", year: 1992, fillsGap: true, note: "The film is here. Seasons 1–2 are free on Pluto TV." },
      { title: "Coraline", year: 2009, fillsGap: true, date: "Oct 1", note: "Arrives Oct 1." },
      { title: "The Outsider", year: 2020, note: "Stephen King. A Georgia detective, an impossible murder, and something that isn't human. The closest thing to Lanterns in HBO's catalog." },
      { title: "It: Welcome to Derry", year: 2025, note: "Prequel series to the It films. Derry in 1962, pure small-town-rot atmosphere." },
      { title: "The Third Day", year: 2020, note: "Jude Law. A tidal island off the English coast, a village festival, folk horror. Only 6 episodes." },
      { title: "Task", year: 2025, note: "Mark Ruffalo. From the creator of Mare of Easttown, a Philadelphia-suburbs crime drama." },
      { title: "Lovecraft Country", year: 2020, note: "Jim Crow-era cosmic horror. Uneven, but the good episodes are great." },
      { title: "October Classics", date: "Oct 1", note: "The Shining, The Exorcist, Poltergeist, the Elm Street run, Trick 'r Treat." },
      { title: "Also on HBO Max, already on the Watchlist", note: "The Staircase, The Jinx, Succession." },
      { title: "Also on HBO Max, in the vault", note: "True Detective (incl. S4 Night Country, set in an Alaskan polar night), Sharp Objects, The Night Of, Chernobyl." },
    ],
    peacock: [
      { title: "Universal Monsters", fillsGap: true, date: "Oct 1", note: "Dracula and Frankenstein (1931), The Mummy (1932), The Invisible Man (1933), The Wolf Man (1941), Phantom of the Opera (1943). A weekly double feature is an easy October habit." },
      { title: "Columbo", fillsGap: true, note: "See Comfort Detectives." },
      { title: "Alfred Hitchcock Presents / The Alfred Hitchcock Hour", fillsGap: true, note: "See Anthology Nights." },
      { title: "Coraline", year: 2009, fillsGap: true, note: "Here too." },
      { title: "Hysteria!", year: 2024, fillsGap: true, note: "See Satanic Panic." },
      { title: "Mrs. Davis", year: 2023, note: "A nun vs. an all-powerful AI; a quest for the Holy Grail. Wildly weird premise played straight. Pluribus-adjacent." },
      { title: "Crystal Lake", date: "Oct 15", note: "Friday the 13th prequel; Linda Cardellini as Pamela Voorhees." },
      { title: "Unsolved Mysteries", note: "Robert Stack era. The original late-night dread machine." },
      { title: "Also on Peacock, in the vault", note: "Poker Face, Chucky, the Halloween and Scream runs." },
    ],
  },
};
